#
# sets up a docker container for the application, a mongo replica set consisting
# of one node, and migrates the mongo recipe schema to the current version.
#
# To set up a mongo cluster with three nodes instead of just one you must
# uncomment and comment code in this file, and in the two other files.
#
# In this file:
#  1. Uncomment the sections for "mongo2" and "mongo3".
#  2. In the "mongo_setup" section, uncomment the "depends_on" items
#     "mongo2" and "mongo3".
#  3. In the "volumes" section, uncomment the entries for "mongo-2-recipes-data"
#     "mongo-3-recipes-data".
#
# In the "deployment/mongo/mongo_setup.sh" file:
#  1. Comment out the "mongosh" command with the replica set holding only one node.
#  2. Uncomment the "mongosh" command with the replica set holding the three nodes.
#  3. Comment out the "cd" section with the two "mongo import" commands where the
#     host that refers only to "mongo1".
#  4. Uncomment the "cd" section with the two "mongo import" commands where the
#     host that refers two to "mongo1,mongo2,mongo3".
#  5. Comment out the "mongosh" command at the end of the file whose host refers
#     only to "mongo1".
#  6. Uncomment out the "mongosh" command at the end of the file whose host refers
#     to "mongo1,mongo2,mongo3".
#
# In the "deployment/mongo/migrate-mongo-config.js" file:
#  1. Comment out the "mongodb.url" that refers only to "mongo1"
#  2. Uncomment the "mongodb.url" that refers to "mongo1,mongo2,mongo3"
#
services:

  # environment variables used by docker compose are in the .env
  # environment file that is written by an external process.
  #
  # (generally for deploying recipeBook, you are using the
  # "deploy_recipes_mongo_with_auth.sh" and this generates the
  # .env file.)
  app:

    container_name: recipes-server

    # want to wait until the "mongo_setup" finishes successfully
    # before starting this. largely this is so that we can do
    # a migrate-mongo to bring the database to the current version
#    depends_on:
#      mongo_setup:
#        condition: service_completed_successfully
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy

    # build the image from the Dockerfile in this same directory
    build: .

    # todo IP address on raspberry had to be updated to 192.168.1.58
    ports:
      - 127.0.0.1:8081:3000
    working_dir: /usr/app
    volumes:
      - recipes-app-data:/usr/app

    # variables for next auth (need to move the secret into a secret)
    # (holds the next-auth secret and should be unique for your deployment)
    env_file:
      - deployment/.env.compose

#    # general next-auth variables that will likely remain the same
#    # across deployments
#    environment:
#      NEXTAUTH_URL_INTERNAL: 'http://localhost:3000'
#      NEXTAUTH_URL: 'http://localhost:8081'
#      NEXTAUTH_SECRET: 'caa8eeccc7d0e6e3f02d7f3a0c21bd43ed30b4f7cfe897448bb92ff4890bf6ef'
#      MONGO_ADMIN_USERNAME: 'looker',
#      MONGO_ADMIN_PASSWORD: 'he%2Dw3nt%2D2%2DtHehou5eto%2Dlo0k',
#      MONGO_NODES: 'mongo1,mongo2,mongo3',


    # install all the dependencies and start the dev server
#    command: sh -c "npm run start"

  # generates a key file that is used by the mongo cluster for internal cluster
  # authentication. each node of the mongo cluster needs this key file
  mongo_security_setup:
    image: mongo:latest
    volumes:
      - ./:/deployment
    restart: "no"
#    entrypoint: [ "bash", "/deployment/deployment/mongo/mongo_security_setup.sh" ]
    command: sh -c "mkdir -p /deployment/deployment/mongo/generated && /deployment/deployment/mongo/mongo_security_setup.sh"

  # set up the mongo cluster
  mongo1:
    image: mongo:latest
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27027:27017

    # ensure that the key-file has been generated successfully so that
    # it can be used in the entrypoint
    depends_on:
      mongo_security_setup:
        condition: service_completed_successfully

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - mongo-1-recipes-data:/data/db
      - ./deployment/mongo/generated/:/data/authentication
      - ./deployment/mongo:/data/setup

    restart: always

    healthcheck:
      test: [ "CMD", "mongod", "--version" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
#      start_interval: 5s

    # by default mongodb uses the WiredTiger storage engine
    entrypoint: [
      "mongod",
      "--replSet", "recipesReplicaSet",
      "--bind_ip", "localhost,mongo1",
      "--keyFile", "/data/authentication/internal-replica-key-file.key"
    ]

  mongo2:
    image: mongo:latest
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27028:27017

    # ensure that the key-file has been generated successfully so that
    # it can be used in the entrypoint
    depends_on:
      mongo_security_setup:
        condition: service_completed_successfully

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - mongo-2-recipes-data:/data/db
      - ./deployment/mongo/generated/:/data/authentication
      - ./deployment/mongo:/data/setup

    restart: always

    healthcheck:
      test: [ "CMD", "mongod", "--version" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
#      start_interval: 5s

    entrypoint: [
      "mongod",
      "--replSet", "recipesReplicaSet",
      "--bind_ip", "localhost,mongo2",
      "--keyFile", "/data/authentication/internal-replica-key-file.key"
    ]

  mongo3:
    image: mongo:latest
    hostname: mongo3
    container_name: mongo3
    ports:
      - 27029:27017

    # ensure that the key-file has been generated successfully so that
    # it can be used in the entrypoint
    depends_on:
      mongo_security_setup:
        condition: service_completed_successfully

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

    volumes:
      - mongo-3-recipes-data:/data/db
      - ./deployment/mongo/generated/:/data/authentication
      - ./deployment/mongo:/data/setup

    restart: always

    healthcheck:
      test: [ "CMD", "mongod", "--version" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 0s
#      start_interval: 5s

    entrypoint: [
      "mongod",
      "--replSet", "recipesReplicaSet",
      "--bind_ip", "localhost,mongo3",
      "--keyFile", "/data/authentication/internal-replica-key-file.key"
    ]

# todo remove this, the set up scripts need to do this because now the order is
# todo different for authenticated cluster (may be able to add back into compose)
#  mongo_setup:
#    image: mongo:latest
#    depends_on:
#      mongo1:
#        condition: service_healthy
#      mongo2:
#        condition: service_healthy
#      mongo3:
#        condition: service_healthy
#    volumes:
#      - ./:/deployment
#    restart: "no"
#    entrypoint: ["bash", "/deployment/deployment/mongo/mongo_setup.sh"]

volumes:
  recipes-app-data:
  mongo-1-recipes-data:
  mongo-2-recipes-data:
  mongo-3-recipes-data:
