# sets up a docker container for the application, a mongo replica set consisting
# of one node, and migrates the mongo recipe schema to the current version.
services:

  app:
    image: node:alpine
    depends_on:
      - mongosetup
    environment:
      NEXTAUTH_SECRET: caa8eeccc7d0e6e3f02d7f3a0c21bd43ed30b4f7cfe897448bb92ff4890bf6ef
      NEXTAUTH_URL: 'http://localhost:8081'

    # install all the dependencies and start the dev server
    command: sh -c "npm install && npm rebuild bcrypt && npm run build && npm install -g migrate-mongo && cd deployment/mongo; migrate-mongo up; cd /usr/app && npm run start"
    #  && npm install -g migrate-mongo && cd deployment/mongo; migrate-mongo up; cd /usr/app
    build: .
    ports:
      - 127.0.0.1:8081:3000
    working_dir: /usr/app
    volumes:
      - ./:/usr/app

  # set up the mongo cluster
  mongo1:
    image: mongo:6
    hostname: mongo1
    container_name: mongo1
    ports:
      - 27027:27017
    volumes:
      - mongo-1-recipes-data:/data/db
    restart: unless-stopped
    entrypoint: ["mongod", "--replSet", "recipesReplicaSet", "--bind_ip", "localhost,mongo1"]

  mongo2:
    image: mongo:6
    hostname: mongo2
    container_name: mongo2
    ports:
      - 27028:27017
    volumes:
      - mongo-2-recipes-data:/data/db
    restart: unless-stopped
    entrypoint: ["mongod", "--replSet", "recipesReplicaSet", "--bind_ip", "localhost,mongo2"]

  mongo3:
    image: mongo:6
    hostname: mongo3
    container_name: mongo3
    ports:
      - 27029:27017
    volumes:
      - mongo-3-recipes-data:/data/db
    restart: unless-stopped
    entrypoint: ["mongod", "--replSet", "recipesReplicaSet", "--bind_ip", "localhost,mongo3"]

  mongosetup:
    image: mongo:6
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./:/deployment
    restart: "no"
#    command: "find / -name 'mongo_setup.sh'"
    entrypoint: ["bash", "/deployment/deployment/mongo/mongo_setup.sh"]

volumes:
  mongo-1-recipes-data:
  mongo-2-recipes-data:
  mongo-3-recipes-data: